apiVersion: apps/v1beta1  
kind: Deployment  
metadata:  
  name: containerizedmvc  
spec:  
  replicas: 1  
  strategy:  
    rollingUpdate:  
      maxSurge: 1  
      maxUnavailable: 1  
  minReadySeconds: 5   
  template:  
    metadata:  
      labels:  
        app: containerizedmvc  
    spec:  
      containers:  
      - name: mysuperaspcore  
        image: mysuperaspcore  
        ports:  
        - containerPort: 80  
        resources:  
          requests:  
            cpu: 250m  
          limits:  
            cpu: 500m
        imagePullPolicy: IfNotPresent
        
---  
apiVersion: apps/v1beta1  
kind: Deployment  
metadata:  
  name: webapinetcoremvc  
spec:  
  replicas: 1  
  strategy:  
    rollingUpdate:  
      maxSurge: 1  
      maxUnavailable: 1  
  minReadySeconds: 5   
  template:  
    metadata:  
      labels:  
        app: webapinetcoremvc  
    spec:  
      containers:  
      - name: aspnetwebapi  
        image: aspnetwebapi  
        ports:  
        - containerPort: 80  
        resources:  
          requests:  
            cpu: 250m  
          limits:  
            cpu: 500m
        imagePullPolicy: IfNotPresent
        
---  
apiVersion: v1  
kind: Service  
metadata:  
  name: containerizedmvc  
spec:  
  type: NodePort  
  ports:  
  - port: 80  
    nodePort: 30663  
  selector:  
    app: containerizedmvc  

---  
apiVersion: v1  
kind: Service  
metadata:  
  name: webapinetcoremvc  
spec:  
  type: NodePort  
  ports:  
  - port: 80
    nodePort: 30664  
  selector:  
    app: webapinetcoremvc  